### ISSUE TITLE
Error on decks

### ISSUE THREAD

**Issue by ExtremeCoolDude** [gregorias/anki-code-highlighter#60]
I'm using a premade deck and whenever I try to highlight, I get this error : 

`The selected code contains partial HTML tags.  Clean up your code snippet in the HTML editor (https://docs.ankiweb.net/editing.html#editing-features) before highlighting.`

![image](https://github.com/gregorias/anki-code-highlighter/assets/50034073/23f18395-0d37-47b3-b0e6-a4dd4a9e4bdc)

It's not very practical to edit every html card in a premade deck with 1000 cards. I am wondering if there is a solution. Thanks!

**Comment by gregorias** [comment]
Hi @ExtremeCoolDude,

Regarding the first issue, a solution would be to implement an automatic way to clean up HTML from cards. You could also write a Python script yourself that cleans up your cards.  
At this moment, I don't have the capacity to work on that but I welcome contributions.

Regarding the second issue, could you open a bug ticket and provide reproduction steps? I can't reproduce your issue, so I don't know how to fix it.

Thank you for reporting.

**Comment by ExtremeCoolDude** [comment]
Steps to reproduce: 

1. Create a test deck
2. Create a basic card front and back like this : 

![image](https://github.com/gregorias/anki-code-highlighter/assets/50034073/81af2f5f-558d-42c3-91e7-d39863cd73a0)


on back : press enter twice to have two <br> tags, create a `<div>  a </div>` in the html editor

3. Highlight a block of test to add to test block by dragging the cursor over text
3. Press ctrl + ' to invoke the add on: 

This happens on my machine : 

![image](https://github.com/gregorias/anki-code-highlighter/assets/50034073/ba3dcc55-0c42-4cf4-b130-002f121da5be)


Please let me know if this is not reproducible.  That would mean the issue is with my Anki version.  (Version ⁨2.1.61 (0c1eaf4c)⁩
Python 3.9.15 Qt 6.4.2 PyQt 6.4.0)

**Comment by gregorias** [comment]
WAI. You are selecting a text block with HTML tags in them, which the current tool is not sophisticated enough to handle. You need to clean up HTML tags before applying a highlight.

**Comment by ExtremeCoolDude** [comment]
WAI ?  I'm just a tech hobbyist, with no formal education in tech. Maybe make the message clear to something like " remove all html code from editor"  instead of "remove partial tags"

**Comment by gregorias** [comment]
I've taken a deeper look into this and made the error message clearer.

I've been mistaken in my previous explanation. The problem is that you are selecting a partial non-Text node. The background is that I'm using Range.surroundContents to implement essential functionality and it doesn't work with partial nodes (https://developer.mozilla.org/en-US/docs/Web/API/Range/surroundContents). In other words, you just need to make sure you don't select half of div or span or something like that. It should be much better than cleaning entire HTML tags.

I've made the error message clearer in the latest CL to address the issue. I don't intend to make the code work with partial selection as I don't have the time to do that. :(

Thank you for reporting and your patience. Let me know though if you have further ideas on how to make this better.
