### ISSUE TITLE
Adding additional highlighting/styling with highlight.js

### ISSUE THREAD

**Issue by moltencrux** [gregorias/anki-code-highlighter#62]
I'm using `highlight.js` for most of the code examples in my cards and have been quite impressed with it.  Is it possible to add additional styling to parts of the code beyond what the current highlighting scheme provides? There are some cards where I'd like to underline a function, put something in italics or draw a box around a line of code to emphasize it, but haven't had any luck.  I saw  [this stackoverflow post](https://stackoverflow.com/questions/29173081/emphasizing-lines-with-highlight-js) where they seem to achieve something similar with highlight.js, but when I tried something similar, it seems to be overridden in the final rendering.  Below is a card field where I attempted to achieve this effect.
```
<pre style="display:flex;"><code class="language-python">def <mark>myfunc</mark>(x)
    print('Hello!')
    
</code></pre>
```
Is using pygments my only option here? or is there something else I can try?.

**Comment by gregorias** [comment]
I'm a bit busy in my life right now. I'll take look as soon as I find some time.

**Comment by moltencrux** [comment]
Understood.  Thanks so much!

**Comment by gregorias** [comment]
How about you try out Pygments highlighter for this purpose? With Pygments, you may attach arbitrary markup to the HTML code of a note.

For example, here I've manually added `style="background-color: red"` to highlight the hello string.

<img width="469" alt="image" src="https://github.com/gregorias/anki-code-highlighter/assets/722385/55f571fd-950e-4776-a2b2-d433c7f14937">

<img width="252" alt="image" src="https://github.com/gregorias/anki-code-highlighter/assets/722385/b5570941-678f-4406-b355-1ff80f90fb12">

I'm closing this issue, because I believe it should be enough. Let me know if I missed something.
