### ISSUE TITLE
[Enhancement] Make it compatible with Simple Cloze Overlapper 

### ISSUE THREAD

**Issue by cocowash** [gregorias/anki-code-highlighter#86]
I really like this add-on, but it seems that it's incompatible with the template Simple Cloze Overlapper, which in my opinion is better that the default cloze that Anki comes with. 
[https://github.com/michalrus/anki-simple-cloze-overlapper](https://github.com/michalrus/anki-simple-cloze-overlapper)

The problem is that out of the box the add-on has some conflicts with the front template and the screen remains white. 
My current workaround is to eliminate the add-on in the front template and make it work only on the back template. hope this help someone that also uses this template. 

Cheers.

**Comment by gregorias** [comment]
Hi @cocowash,

Thanks so much for reporting this. I’ll take a look as soon as possible. Might take O(days) or O(weeks) depending on what life throws at me.

**Comment by gregorias** [comment]
Use [this PR of mine](https://github.com/michalrus/anki-simple-cloze-overlapper/pull/17), and you’ll be fine.

**Comment by cocowash** [comment]
Hi @gregorias, 
I have tried your pull request and now the front field is render but also i'm experiencing a weird bug that sometimes it highlights another sibling as the asked question instead of the correct sibling. 
for example, let's suppose that the card has 2 clozes in it. It can highlight cloze number 2 as the question asked, while in the back it shows the answer for cloze one.  For example: 
![Captura de pantalla 2024-06-23 155041](https://github.com/gregorias/anki-code-highlighter/assets/62455662/269fd824-f77d-461b-804b-337ad9fd23fa)
![Captura de pantalla 2024-06-23 155219](https://github.com/gregorias/anki-code-highlighter/assets/62455662/bd07349a-7428-4195-b9e8-d3bf420d35a7)
I disabled all my plugins and the bug persisted, it only went away after erasing the code from the front template. 
Have you any idea what could be causing this? 
Thanks for the support, cheers.

**Comment by gregorias** [comment]
I don’t have an idea yet. My experience from “fixing” the original issue is that 
[Overlapper’s code](https://github.com/michalrus/anki-simple-cloze-overlapper) is just fragile. Written for specific circumstances. The PR fixes an issue in Overlapper’s code, for instance. Highlighter didn’t do anything incorrectly.

I suggest that it would be more appropriate to direct this issue to that plugin’s maintainer, as I strongly suspect that’s where the issue lies.

If you want to debug the issue yourself, I recommend [the WebView inspector](https://ankiweb.net/shared/info/31746032). You can trace through code with `console.log` with that to see for yourself what’s happening.
